//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbplayers.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class playersdbEntities : DbContext
    {
        public playersdbEntities()
            : base("name=playersdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<Cityes> Cityes { get; set; }
        public virtual DbSet<Clubs> Clubs { get; set; }
        public virtual DbSet<National_teams> National_teams { get; set; }
        public virtual DbSet<Nations> Nations { get; set; }
        public virtual DbSet<Place_birth> Place_birth { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Technical_sponsors> Technical_sponsors { get; set; }
        public virtual DbSet<Working_leg> Working_leg { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
    }
}
